### ISSUE TITLE
Design HDACore Schema for Outpatient Prescriptions

### ISSUE THREAD

**Issue by chris-githu** [palladium-group/HDA#2]
Design HDACore Schema for Outpatient Prescriptions
@jongitau

**Comment by chris-githu** [comment]
@jongitau 
For outpatient prescriptions we need the following dimensions for now
- Patient
- Provider
- Time
- Org Unit > Health Facility
- Drug > Drug Class

FYI @Ejimba

**Comment by jongitau** [comment]
@chris-githu,@Ejimba  in the google drive folder shared earlier -https://drive.google.com/drive/folders/1HzSIzW69OiJqUk4_q-XMRw8VROh1Bud9

The following have been added - 

- PrescriptionsSchema.docx - word document with schema design

- PrescriptionsSchema.sql   - a script to create tables shown in PrescriptionsSchema design document

- druglist - SQL dump of sample drugs dummy data 

 dumps for drug classes and sample prescriptions will follow

**Comment by jongitau** [comment]
@chris-githu,@Ejimba in the google drive shared folder  -https://drive.google.com/drive/folders/1HzSIzW69OiJqUk4_q-XMRw8VROh1Bud9

Run the following scripts on your DBs to populate drugs, drug classes, patients and random prescriptions for testing

- DrugsDump.sql

- drugclasslookupsDump.sql

- PatientsDump.sql

- prescriptionsDummyData.sql

**Comment by jongitau** [comment]
@chris-githu,@Ejimba -  shared folder has following schema  files

- HDACore Schema Definition 

- HDACore ER Diagram

confirm if the initial `HDACore Schema Definition` document is adequate in terms of layout & table summary as i continue adding other models to it
